student:
  name: xiaohua
  password: 123456
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smbms
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    username: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.pojo


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
